### ISSUE TITLE
Dead link in the Configure AWS Access section

### ISSUE THREAD

**Issue by baniol** [serverless/platform#3]
Hi,
the link on `docs/event-gateway/getting-started.md` in the `Configure AWS Access Keys in Serverless Framework` section leads to the cat on a desert .

**Comment by alexdebrie** [comment]
Oops! Thanks for reporting, @baniol. Fixed [here](https://github.com/serverless/platform/commit/ec89067d59e09408d6bdf12ab6f5c539b3490426)
