### ISSUE TITLE
CLI only login

### ISSUE THREAD

**Issue by 0snug0** [serverless/platform#5]
Similar to [gcloud auth `--no-launch-browser`](https://cloud.google.com/sdk/gcloud/reference/auth/login) will provide a URL to login.

> If you'd rather authorize without a web browser but still interact with the command line, use the --no-launch-browser flag.

**Comment by manwaring** [comment]
The ability to use a key/token or any kind of non-browser authentication is pretty important for all my personal and client projects - without it we won't be able to use the dashboard part of the platform at all b/c can't integrate with automated build/deploy tools

**Comment by alexdebrie** [comment]
@0snug0 @manwaring Great points. The `SERVERLESS_ACCESS_KEY` environment variable is designed to allow headless access (e.g. in a CI/CD tool). There is an issue with it right now. You can follow along here: https://github.com/serverless/serverless/issues/5182.

I'll keep this open if you have any follow-ups but feel free to close if the other issue satisfies your needs.

**Comment by SpainTrain** [comment]
I suggest closing - I had the same issue as @0snug0 and the env var resolved it. Thanks!

**Comment by alexdebrie** [comment]
Closing! Thanks, @SpainTrain !
